# Site settings
title: arbennett.github.io 
email: bennett.andr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Until next time...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://arbennett.github.io" # the base hostname & protocol for your site

github_username:  arbennett
email_username:  bennett.andr@gmail.com

# Build settings
markdown: rdiscount #kramdown
